version: "3"
services:
  mysql:
    image: mysql:8.0.21
    restart: "no"
    environment:
      MYSQL_USER: cv
      MYSQL_PASSWORD: cv
      MYSQL_DATABASE: cv
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 127.0.0.1:3306:3306
    command: --character-set-server=utf8 --collation-server=utf8_bin --max-allowed-packet=67108864

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    restart: "no"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 127.0.0.1:3307:80
