-- MySQL Script generated by MySQL Workbench
-- Sun Oct  4 09:04:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room` (
  `id_room` INT NOT NULL,
  `max_capacity` INT NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `row_count` INT NOT NULL,
  PRIMARY KEY (`id_room`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chair`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chair` (
  `id_chair` INT NOT NULL,
  `id_room` INT NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `row_number` INT NOT NULL,
  `column_number` INT NOT NULL,
  PRIMARY KEY (`id_chair`),
  INDEX `fk_chair_room_idx` (`id_room` ASC) VISIBLE,
  CONSTRAINT `fk_chair_room`
    FOREIGN KEY (`id_room`)
    REFERENCES `mydb`.`room` (`id_room`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
